ToDo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('home/', views.home, name="home"),
    path('logout/', views.logout, name="logout"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class ToDo(models.Model):
	todo_id = models.CharField(max_length=255, primary_key=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	todo = models.TextField()
	is_completed = models.BooleanField(default=False)
	# due_date = models.DateField()
	date_created = models.DateField()

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.contrib.auth import logout as logout_user
from .models import ToDo
import uuid
from datetime import date

# Create your views here.
def index(request):
	user = request.user
	return render(request, "index.html", {"user": user})

def signup(request):
	if request.method == "POST":
		username = request.POST["username"]
		email = request.POST["email"]
		password = request.POST["password"]
		confirm_password = request.POST["confirm_password"]

		if password!=confirm_password:
			messages.error(request, "Password and Confirm Password should be same")
			return redirect('main:signup')

		username_already_exists = list(User.objects.filter(username=username))

		if len(username_already_exists)!=0:
			messages.info(request, "User with username {} already exists".format(username))
			return redirect('main:signup')

		email_already_exists = list(User.objects.filter(email=email))

		if len(email_already_exists)!=0:
			messages.info(request, "User with email {} already exists".format(email))
			return redirect('main:signup')

		try:
			User.objects.create_user(username=username, email=email, password=password)
			messages.success(request, "username {} registered successfully".format(username))
			return redirect("main:login")
		except Exception as e:
			raise e
	user = request.user
	return render(request, "signup.html", {"user": user})

def login(request):
	if request.method == "POST":
		username = request.POST["username"]
		password = request.POST["password"]

		try:
			user = authenticate(username=username, password=password)
		except Exception as e:
			raise e

		if user is not None:
			try:
				login_user(request, user)
				is_loggedin = True
			except Exception as e:
				raise e

			# messages.success(request, "Logged in successfully")
			return redirect('main:home')

	user = request.user
	return render(request, "login.html", {"user": user})

def home(request):
	user = request.user
	if request.method == "POST":
		if 'new' in request.POST:
			user_object = User.objects.get(username=user)
			todo = request.POST["todo"]
			todo_id = str(uuid.uuid4())
			date_created = date.today()
			ToDo.objects.create(todo_id = todo_id, user=user_object, todo=todo, date_created=date_created)
		elif 'archive' in request.POST:
			todo_id = request.POST["archive"]
			ToDo.objects.filter(todo_id=todo_id).update(is_completed=True)
			return redirect("main:home")
		elif 'delete' in request.POST:
			todo_id = request.POST["delete"]
			ToDo.objects.filter(todo_id=todo_id).delete()
			messages.success(request, "ToDo deleted successfully!")
			return redirect("main:home")
		elif 'unarchive' in request.POST:
			todo_id = request.POST["unarchive"]
			ToDo.objects.filter(todo_id=todo_id).update(is_completed=False)
			return redirect("main:home")

		return redirect('main:home')
	todos = ToDo.objects.filter(user=user, is_completed=False).order_by("-date_created")
	completed_todos = ToDo.objects.filter(user=user, is_completed=True).order_by("-date_created")
	return render(request, "home.html", {"user": user, "todos": todos, "completed_todos": completed_todos} )

def logout(request):
	logout_user(request)
	# user = request.user
	return redirect("main:index")

main/templates/headers.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

main/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	{% include 'headers.html' %}
</head>
<body>
	{% include 'navbar.html' %}
	{% include 'messages.html' %}

	<form method="post">
		{% csrf_token %}
		<div class="form-group">
	        <label class="lead">New To-Do:</label>
	        <input id="todo-box" type="text" class="form-control" placeholder="Enter you new to-do here..." name="todo" required>
	  	</div>
	  	<button type="submit" class="btn btn-primary" name="new" id="addbutton">Add New Todo</button>
	 </form>

<!-- 	<div class="container">
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
   		 Archived ToDo
  		</button>
	</div> -->

	 <form method="post">
	 	{% csrf_token %}

	 	<div class="modal fade" id="myModal">
	   	 	<div class="modal-dialog">
		      <div class="modal-content">
		      
		        <div class="modal-header">
		          <h4 class="modal-title">Modal Heading</h4>
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		        </div>
		        
		        <div class="modal-body">
		          	<table class="table table-dark table-striped">
					    <thead>
					      <tr>
					        <th>Todo</th>
					        <th>Date Created</th>
					        <th>Unarchive</th>
					      </tr>
					    </thead>
					    <tbody>
					    	{% for todo in completed_todos %}
					    		<tr>
							        <td>{{todo.todo}}</td>
							        <td>{{todo.date_created}}</td>
							        <td><button type="submit" value="{{todo.todo_id}}" name="unarchive" class="btn btn-info">Unarchive</button></td>
					      		</tr>
					    	{% endfor %}
					    </tbody>
		  			</table>
		        </div>
		        
		        <div class="modal-footer">
		          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
		        </div>
		        
		      </div>
		    </div>
	  	</div>
	  	
		<div class="container">
		  <h2>
		  	{{user}}'s ToDo List
		  	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="archived">
   		 		Archived ToDo
  			</button> 
		  </h2>
		  <!-- <p>View/Edit/Delete</p>   -->         
		  <table class="table table-dark table-striped">
		    <thead>
		      <tr>
		        <th>Todo</th>
		        <th>Date Created</th>
		        <th>Completed?</th>
		        <th>Mark as Complete</th>
		        <th>Delete</th>
		      </tr>
		    </thead>
		    <tbody>
		    	{% for todo in todos %}
		    		<tr>
				        <td>{{todo.todo}}</td>
				        <td>{{todo.date_created}}</td>
				        <td>{% if todo.is_completed %}Yes{% else %}No{% endif %}</td>
				        <td><button type="submit" value="{{todo.todo_id}}" name="archive" class="btn btn-info">Done</button></td>
				        <td><button type="submit" value="{{todo.todo_id}}" name="delete" class="btn btn-danger">Delete</button></td>
		      		</tr>
		    	{% endfor %}
		    </tbody>
		  </table>
		</div>
	</form>

</body>
</html>

main/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>To-Do App</title>
	{% include 'headers.html' %}
</head>
<body style="background-color: #ff00f8;">
	{% include 'navbar.html' %}
	<!-- <img src="static/images/81nia28xsOL._SY355_.jpg" class="center"> -->
	<h1 class="ml6">
  		<span class="text-wrapper">
    		<span class="letters">ToDos In One Place</span>
  		</span>
	</h1>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js"></script>
	<script type="text/javascript" src="static/js/script.js"></script>
</body>
</html>

main/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login Form</title>
  {% include 'headers.html' %}
</head>
<body>
  {% include 'navbar.html' %}
  {% include 'messages.html' %}
<div class="container">
  <h2>Login form</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Username" name="username" required>
    </div>
    <div class="form-group">
      <input type="password" class="form-control" placeholder="Password" name="password" required>
    </div>
    
    <button type="submit" class="btn btn-primary">Login</button>
    New user?. First signup <a href="{% url 'main:signup' %}">here</a>
  </form>
</div>

</body>
</html>

main/templates/messages.html
{% if messages %}
	{% for message in messages %}
	 	{{message}}
	{% endfor %}
{% endif %}

main/templates/navbar.html
<nav class="navbar navbar-expand-sm bg-info navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Todo APP</a>
    </li>
    <li class="nav-item" {% if user.is_authenticated %} hidden {% endif %}>
      <a class="nav-link" href="{% url 'main:signup' %}">Signup</a>
    </li>
    <li class="nav-item" {% if user.is_authenticated %} hidden {% endif %}>
      <a class="nav-link" href="{% url 'main:login' %}">Login</a>
    </li>
    <li class="nav-item" {% if not user.is_authenticated %} hidden {% endif %}>
      <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
    </li>
    <li class="nav-item">
	    {% if user.is_authenticated %}
	    	<a class="nav-link"><strong>Welcome {{user}}</strong></a>
	    {% endif %}
	</li>
  </ul>
</nav>

main/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Signup Form</title>
  {% include 'headers.html' %}
</head>
<body>
  {% include 'navbar.html' %}
  {% include 'messages.html' %}
  <div class="container">
    <h2>Signup form</h2>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label>Username:</label>
        <input type="text" class="form-control" placeholder="Enter username" name="username" required>
      </div>
      <div class="form-group">
        <label>Email:</label>
        <input type="email" class="form-control" placeholder="Enter email" name="email" required>
      </div>
      <div class="form-group">
        <label>Password:</label>
        <input type="password" class="form-control" placeholder="Enter password" name="password" required>
      </div>
      <div class="form-group">
        <label>Confirm Password:</label>
        <input type="password" class="form-control" placeholder="Re-Enter password" name="confirm_password" required>
      </div>
      <button type="submit" class="btn btn-primary">Register</button>
      Already Registered?. Login <a href="{% url 'main:login' %}">here</a>
    </form>
  </div>

</body>
</html>